// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: addsrv.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sum方法的请求参数
type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_addsrv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SumRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

// Sum方法的响应
type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_addsrv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{1}
}

func (x *SumResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SumResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Concat方法的请求参数
type ConcatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatRequest) Reset() {
	*x = ConcatRequest{}
	mi := &file_addsrv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatRequest) ProtoMessage() {}

func (x *ConcatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatRequest.ProtoReflect.Descriptor instead.
func (*ConcatRequest) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{2}
}

func (x *ConcatRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *ConcatRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

// Concat方法的响应
type ConcatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcatResponse) Reset() {
	*x = ConcatResponse{}
	mi := &file_addsrv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatResponse) ProtoMessage() {}

func (x *ConcatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addsrv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatResponse.ProtoReflect.Descriptor instead.
func (*ConcatResponse) Descriptor() ([]byte, []int) {
	return file_addsrv_proto_rawDescGZIP(), []int{3}
}

func (x *ConcatResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ConcatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_addsrv_proto protoreflect.FileDescriptor

const file_addsrv_proto_rawDesc = "" +
	"\n" +
	"\faddsrv.proto\x12\x06addsrv\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\n" +
	"SumRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\";\n" +
	"\vSumResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\rConcatRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\">\n" +
	"\x0eConcatResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa9\x01\n" +
	"\x03Add\x12J\n" +
	"\x03Sum\x12\x12.addsrv.SumRequest\x1a\x13.addsrv.SumResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/add/sum\x12V\n" +
	"\x06Concat\x12\x15.addsrv.ConcatRequest\x1a\x16.addsrv.ConcatResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/add/concatB`\n" +
	"\n" +
	"com.addsrvB\vAddsrvProtoP\x01Z\raddsrv3/proto\xa2\x02\x03AXX\xaa\x02\x06Addsrv\xca\x02\x06Addsrv\xe2\x02\x12Addsrv\\GPBMetadata\xea\x02\x06Addsrvb\x06proto3"

var (
	file_addsrv_proto_rawDescOnce sync.Once
	file_addsrv_proto_rawDescData []byte
)

func file_addsrv_proto_rawDescGZIP() []byte {
	file_addsrv_proto_rawDescOnce.Do(func() {
		file_addsrv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addsrv_proto_rawDesc), len(file_addsrv_proto_rawDesc)))
	})
	return file_addsrv_proto_rawDescData
}

var file_addsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_addsrv_proto_goTypes = []any{
	(*SumRequest)(nil),     // 0: addsrv.SumRequest
	(*SumResponse)(nil),    // 1: addsrv.SumResponse
	(*ConcatRequest)(nil),  // 2: addsrv.ConcatRequest
	(*ConcatResponse)(nil), // 3: addsrv.ConcatResponse
}
var file_addsrv_proto_depIdxs = []int32{
	0, // 0: addsrv.Add.Sum:input_type -> addsrv.SumRequest
	2, // 1: addsrv.Add.Concat:input_type -> addsrv.ConcatRequest
	1, // 2: addsrv.Add.Sum:output_type -> addsrv.SumResponse
	3, // 3: addsrv.Add.Concat:output_type -> addsrv.ConcatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_addsrv_proto_init() }
func file_addsrv_proto_init() {
	if File_addsrv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addsrv_proto_rawDesc), len(file_addsrv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addsrv_proto_goTypes,
		DependencyIndexes: file_addsrv_proto_depIdxs,
		MessageInfos:      file_addsrv_proto_msgTypes,
	}.Build()
	File_addsrv_proto = out.File
	file_addsrv_proto_goTypes = nil
	file_addsrv_proto_depIdxs = nil
}
